lib/sprockets/railtie.rb
Alright, @rafaelfranca
Heres the idea for moving the `append_assets_path` into this plugin.
Then in rails/master we could completely remove `config.assets` and this guy. This code would still cover people running Rails 4.2. And eventually we can remove the guard when we only need to support Rails 5.
Related discussion
* https://github.com/rails/rails/pull/18607
=> Import append_assets_path initializer

lib/sprockets/railtie.rb, test/test_railtie.rb
Now the default for dev and prod mode in Rails initial templates.
Change going into 3.x line.
=> Enable digest by default

lib/sprockets/rails/task.rb, lib/sprockets/railtie.rb, test/test_railtie.rb
#220 causes a slight regression but brings up this weird issue again.
If `config.assets.compile = false` in `production.rb` than you can't even do `rake assets:precompile`.
This is a little work around to force the environment to build even in this case.
@rafaelfranca the environment weirdness between `rake assets:precompile` has always bugged me. Given 3.x can have backwards incompatible changes, have any idea for directions we can move into to make this more clear?
I really wish `rake assets:precompile` would work no matter what and always minified the assets even in RAILS_ENV=development. Would like to make it easier for people who compile assets in an isolate environment and upload them to a CDN. This sometimes happens locally on there machine and othertimes in production like …
=> Always initialize assets environment in rake task

README.md, lib/sprockets/rails/helper.rb, test/fixtures/bar.js, test/test_helper.rb
Sprockets 3.x builds in some plumbing for getting [SRI](http://www.w3.org/TR/SRI/) hashes. This next step exposes the API at the Rails asset tag helper level.
``` ruby
javascript_include_tag :application, integrity: true
```
* The `integrity` format is still a little in flux. The format is generated in Sprockets itself, so spec changes *may* require core changes but nothing at the view level. The `integrity` attribute itself seems pretty established.
* `integrity: true` only works on Sprockets assets, not on `public/` static ones. It'd be cool if at some point in the future, Rails bakes this in directly and provides an asset integrity hook similar to the current `compute_asset_path` hook.
* Base branch targets `master` which is currently released as 3.x beta gems. This isn't going into …
=> Experimental SRI support

.travis.yml, test/test_helper.rb, test/test_railtie.rb, test/test_task.rb
These fixes aren't 100% yet, since some tests are failing due mismatched digests, even though we read the digest directly from the asset itself - I'm gonna take a deeper look on this later.
/cc @rafaelfranca @josh
=> Update the test suite to account for named pipelines and the manifest name change.

lib/sprockets/railtie.rb
Now we can compile manifests located at `app/assets/manifest.js` or something like it.
=> Add `app/assets` to the load path.

lib/sprockets/rails/route_wrapper.rb, lib/sprockets/railtie.rb
We can't depend on assets_prefix outside sprockets.
With this, we can create a rails --api without sprockets and `rake routes` wont fail.
After this is merged, we need to patch Rails. I will send a PR there too.
review @spastorino @rafaelfranca 
@zzak paired with me (he did most of the code :smiley_cat:)
=> Move assets route internal decoration.

lib/sprockets/rails/helper.rb, test/fixtures/bundle/index.js, test/fixtures/jquery/bower.json, test/fixtures/jquery/jquery.js, test/test_helper.rb
Theres a few other edge cases that will slip by the `AssetNotPrecompiled` check that are both issues today on 2.x and 3.x.
* `index` assets can **only** be referenced by their shorthand alias and not by the full path
* bower paths must be referenced by their full path and never there shorthand
The index case is annoying and I'm looking to address it in https://github.com/rails/sprockets/pull/36.
Though, I think this check is probably a good idea no matter what happens in sprockets core.
We basically assert that the input `path` which would be passed directly to `manifest.assets` in production matches the `logical_path` as it would be written out to disk.
The check only affects AV helpers, nothing within asset generation within sprockets.
/cc @arthurnn @rafaelfranca @matthewd
=> Prevent alias logical paths passed to asset_path

lib/sprockets/rails/helper.rb, test/test_helper.rb
@rafaelfranca wdyt about just rolling this back? It should fix @dhh's problem in https://github.com/rails/sprockets/pull/36.
=> Revert asset alias check

.travis.yml, gemfiles/Gemfile.rails-5.0.x.sprockets-4.x, lib/sprockets/rails/context.rb, lib/sprockets/rails/helper.rb, lib/sprockets/rails/utils.rb, lib/sprockets/rails/version.rb, lib/sprockets/railtie.rb, sprockets-rails.gemspec, test/fixtures/manifest.js, test/fixtures/not_precompiled.css, test/fixtures/not_precompiled.js, test/test_helper.rb, test/test_task.rb
Now sprockets-rails works with both, sprockets 3.x and sprockets 4.x.
The source maps debug pipeline is available when using sprockets 4.x.
The changes depend on the version of sprockets being specified. (https://github.com/rails/sprockets/pull/64)
=> Add support for Sprockets 4.x.

lib/sprockets/rails/helper.rb, lib/sprockets/rails/utils.rb, lib/sprockets/railtie.rb, test/test_helper.rb
This fixes the regression reported in #234 that @dhh reported. As noted in the commit message that code was a red herring. The problem was that the cache on `precompiled_assets` was being reset every single time by CachedEnvironment because it didn't pull `precompiled_assets` over.
This change moves that method to the Railtie class so that it remains in the env. 
If you want to test this out I made a brand new application to demonstrate the issue and test with (https://github.com/eileencodes/perf_regression_sprockets). 
This regression shows up on running tests that render assets - show that renders a template with application.js and application.css.
cc/ @jeremy 
---
Fix performance regression in Rails helper
Previously reported performance regression #234 was a red herring. The
`Engine` …
=> Fix performance regression in Rails helper

README.md
The `integrity` attribute doesn't include a dash in the digest name.
=> Fix SRI example hash in README

lib/sprockets/rails/helper.rb, lib/sprockets/rails/utils.rb, lib/sprockets/railtie.rb, test/test_helper.rb
* Lazy-load precompiled asset list so it doesn't block boot time
* Memoize it on the app so it doesn't get flushed along with AV instances
* References #265 and #234.
cc @eileencodes
=> Speed up app boot by deferring asset precompile

lib/sprockets/rails/helper.rb, test/test_helper.rb
If an asset manifest is available, we check it for digests first even
if it's stale and a Sprockets environment is available.
We want to check the asset environment first and use the manifest only
when we're precompiled with no Sprockets environment available.
=> Fix stuck assets in dev due to a stale precompiled manifest

README.md, lib/sprockets/rails/helper.rb, lib/sprockets/railtie.rb, test/test_helper.rb, test/test_railtie.rb
* Revert env-first lookup order from #276 to support using both manifest and a live environment in production.
* Default to manifest first, env second. Skip manifest if debug enabled or digests disabled. Skip env if it's unavailable.
* Override with `config.assets.resolve_with = %i[ manifest environment ]`
=> Restore manifest/env asset lookup order and make it configurable

lib/sprockets/rails/version.rb, lib/sprockets/railtie.rb
`app/assets` was added to give `manifest.js` a place to live, but it suggests that `require 'stylesheets/foo.css'` might be the right way to refer to `require 'foo.css'`.
We resolve the overlap and clarify that `manifest.js` is configuration by moving it from `app/assets/` to `app/assets/config/`. Put it up on a pedestal: https://github.com/rails/rails/pull/21794
This reverts #232 and commit 39ecb27f8a8903619e3aa412927fc48ae42c8323, reversing changes made to 3a44d472cca3b7ed924b330c5af1e04de78841af.
=> Drop toplevel `app/assets` load path

lib/sprockets/railtie.rb
The collection of all linked assets can easily grow into the thousands.
Switch O(n) `Array#include?` scans to O(1) `Set#include?` hash lookups.
=> Speed up checks against our cached precompiled-asset list

lib/sprockets/rails/helper.rb
to explain how to remedy the error using the manifest file to link assets/directories/trees.
=> Update the AssetNotPrecompiled error message for Sprockets 4

README.md
Ran into this in a legacy project (https://github.com/rails/sprockets-rails/issues/312). Not sure if this is the best way to help others, but I wanted to suggest something that might help.
Example:
If debug is true and compile is false, assets will not be resolved
by sprockets and will fall back to the standard rails public dir
resolution.
In this situation
`stylesheet_link_tag('application')` will resolve to
`/stylesheets/application.css` instead of
`/assets/application.css`
=> add README note for config flag conflict

README.md, lib/sprockets/railtie.rb
In this commit https://github.com/rails/sprockets-rails/commit/80164cb0b3eae7dc8a6efab7553a7a8ab4e20c10 the `assets` folder looks to be accidentally removed from the cache file store. This causes problems if you're specifically moving that folder between builds.
=> Change default cache location back to original

lib/sprockets/rails/helper.rb, test/fixtures/manifest.js, test/test_helper.rb
Sprockets allow you to create bundles using `bundle_name/index.js` as the file name. If you declare `bundle_name` in your manifest you should not get an `AssetNotPrecompiled` error.
=> Fix the precompile checker with bundle files

lib/sprockets/railtie.rb
Updated the railtie to ignore files with no extensions, such as LICENSE, that cause sprockets to error out on assets compilation.
=> Update railtie to ignore no-extension files

lib/sprockets/rails/helper.rb, lib/sprockets/railtie.rb
When in classes are not cached, we're not in a state where performance matters as much (like development mode) we want to see if any new files have been added to our precompile list by nature of them being added to disk. For example if you add an image  to `images` and you have linked the directory:
```
//= link_directory ../images
```
This change also eliminates the need to restart the server in development when changes are made when using a manifest.js and Sprockets 4.
cc/ @matthewd
=> [Close #321] Double check precompile missing asset

lib/sprockets/rails/helper.rb, lib/sprockets/railtie.rb, test/test_railtie.rb
Raise a descriptive error if specific config file `app/assets/config/manifest.js` is not found when using Sprockets 4.
The `link ../javascripts/application.js` link does not work for me on codetriage.com but `link application.js` does.
The error when a source isn't found should only show how to add that specific source for maximum clarity.
=> Better Errors

README.md, lib/sprockets/rails/helper.rb, lib/sprockets/railtie.rb, test/test_helper.rb, test/test_railtie.rb
@rafaelfranca this PR makes it possible to disable the exception for a missing asset (but still does by default)
tested in a real use-case and this does appear to eliminate the previously discussed first-request delay
let me know if this needs anything more
=> add option to make raising exception for missing assets optional

README.md, lib/sprockets/rails/quiet_assets.rb, lib/sprockets/railtie.rb, test/test_quiet_assets.rb, test/test_railtie.rb
@rafaelfranca @josh 
Builds on and finishes what @route started in #338.
Basically a deprecation of the [`quiet_assets`](https://github.com/evrone/quiet_assets/) gem.
Adds the `config.assets.quiet` option. Defaulted to `false` in all cases. When true, it loads a middleware. That middleware looks at the asset prefix path, and if matches will wrap the given request in a `logger.silence { }` call.
I've added to the `README` but I don't know if/where I should document it further.
=> Silence asset requests with config.assets.quiet 

README.md
Add a note that the SRI attribute is only applied when the Rails app is served over HTTPS. This is something that tripped me up initially, as browsers treat localhost as a secure origin.
Source: https://github.com/rails/sprockets-rails/commit/fdb0df6b7bf890df3a632e754ec7d4e51688662f
=> Add a note that SRI only works over HTTPS

README.md, lib/sprockets/rails/helper.rb, test/test_helper.rb
The spec has been updated since this code was originally written and this no longer requires a Secure Context: https://www.w3.org/TR/SRI/#is-response-eligible-for-integrity-validation
=> Remove requirement of HTTPS for using SRI

README.md, lib/sprockets/rails/helper.rb, lib/sprockets/railtie.rb, test/test_helper.rb
When an asset isn't found the behavior is to pass the string through. For example a valid asset will return a url from pipeline
```
asset_path("application.js")
```
While if you make a typo, you won't get an error or anything, it just falls through:
```
asset_path("app1icati0n.js")
```
Hopefully I don't have to elaborate on why this is bad.
This PR is a child PR to one in Rails that will introduce a `public_asset_path` API.
There are valid reasons for not using the asset pipeline, if you have a purely static asset in the public folder or if you want to link to a static URL in your assets somewhere it makes sense to declare that intention. Eventually we will replace the behavior of the deprecation with an exception so people don't lose hours of their to typos.
We only emit the deprecation …
=> Deprecate asset fallback

lib/sprockets/rails/context.rb
This fixes a problem with being unable to load `ActionView::Helpers::AssetUrlHelper` from L7 in some situations
@rafaelfranca
=> Be more specific with required file

README.md
I changed build status image URL.
Maybe we want to check build status for only master branch. We do not want to see build status for PR.
I referred `rails/rails` build status.
https://github.com/rails/rails/blob/master/README.md
You can see modified README here.
https://github.com/junaruga/sprockets-rails/blob/feature/readme-badge-master/README.md
=> Specify master branch for Travis build status image.

test/test_railtie.rb
I found below test failure in tests.
> https://travis-ci.org/rails/sprockets-rails/jobs/264678491
> Error:
> TestRailtie#test_sprockets_context_helper:
> NoMethodError: undefined method `split' for nil:NilClass
The error was happened for only `$ bundle exec rake test`.
And below cases, when I ran specifying the test file, the error was not happened.
```
$ bundle exec rake test \
TEST=test/test_railtie.rb \
TESTOPTS="--name=test_sprockets_context_helper -v"
...
1 runs, 4 assertions, 0 failures, 0 errors, 0 skips
```
```
$ bundle exec rake test \
TEST=test/test_railtie.rb
...
26 runs, 90 assertions, 4 failures, 0 errors, 0 skips  <- this is another error, as you know. But not this PR's error.
```
Anyway, when I changed `assert_equal nil` to `assert_nil`, it looks ok.
=> Fix a test failure for undefined method `split' for nil:NilClass.

lib/sprockets/rails/helper.rb
Without this, the error prints like this:
```
DEPRECATION WARNING: The asset "application.js" is not present in the asset pipeline.Falling back to an asset that may be in the public folder.
This behavior is deprecated and will be removed.
To bypass the asset pipeline and preserve this behavior,
use the `skip_pipeline: true` option.
```
=> Missing new line in error message

README.md
This PR **removes the badge** for Gemnasium from the README.
That service is defunct.
=> README: Remove Gemnasium badge

.travis.yml
This PR updates the **list of excludes** in CI, so that we are **not** trying to install **Sprockets 4** on older Rubies.
Result: Green build! 💚 
<details>
<summary>Bonus detail</summary>
- Also: drop unused `sudo: false` directive in Travis. See [Travis CI Blog post](https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration) for more details
</details>
=> CI: Exclude older Rubies from trying to install Sprockets 4 which requires Ruby 2.5.0+

lib/sprockets/rails/helper.rb
This is a sibling PR to https://github.com/rails/sprockets/pull/660. This needs to be changed to fix sprockets-rails causing a deprecation warning after the sprockets deprecation warning is fixed.
I've tested this on my Rails app and my test suite passes just fine with this change even if the sprockets change isn't present.
Oddly, this may actually be the only change that's necessary. I don't see any deprecation warning anymore with just this PR, regardless of whether the sprockets change is made or not.
=> Fix Ruby 2.7 deprecation in helper.rb

lib/sprockets/rails/task.rb, test/test_railtie.rb
Don't require ActionView::Base when rake tasks get loaded:
- ### Problem
When running any rake command, Sprockets Rails will autoload
`ActionView::Base` way too early. This creates a broader issue
which I described in detail in rails/rails#38024
This `require` statement was the last attempt to fix a old [issue](https://github.com/rails/rails/issues/9461)
in 2014. TL;DR on the issue is that assets_prefix would
get ignored when precompiling assets.
A lot has change since 2014 in sprockets-rails and after digging
I can confirm that requiring AV::Base is no longer needed.
We don't need it to run assets related rake tasks.
This is thanks thanks of the decoupling between
`Sprockets::Rails::Context` and `Sprockets::Rails::Helper`
in https://github.com/rails/sprockets-rails/commit/32a58f54
cc/ …
=> Don't require ActionView::Base when rake tasks get loaded:

.travis.yml, lib/sprockets/rails/helper.rb, test/test_helper.rb, test/test_railtie.rb
Add ruby 2.7.1 and update patch releases for existing rubies.
=> Update ruby version testing matrix

lib/sprockets/rails/helper.rb, test/test_helper.rb
Because of the change in https://github.com/rails/sprockets-rails/pull/414, [this line](https://github.com/rails/sprockets-rails/blob/master/lib/sprockets/rails/helper.rb#L372) now raises an error with no helpful message on what you should do to fix it:
```
SessionsControllerTest#test_auth_for_invited_user:
ActionView::Template::Error: owner-banner.png
/Users/alex/.rvm/gems/ruby-2.7.2/gems/sprockets-rails-3.2.2/lib/sprockets/rails/helper.rb:372:in `raise_unless_precompiled_asset'
```
Instead, we should raise the new error class added in https://github.com/rails/sprockets-rails/pull/414
This would be a breaking change if you had code that looks like this:
```ruby
begin
@view.javascript_include_tag("not_precompiled")
rescue StandardError => e
puts "error" if e.class == …
```
=> Raise the error that includes an error message

lib/sprockets/rails/asset_url_processor.rb, lib/sprockets/railtie.rb, test/test_asset_url_processor.rb
This is required so that we can use cssbundling-rails and reference images that will receive digested paths
=> Process css files so that they get digested paths for asset files

lib/sprockets/rails/sourcemapping_url_processor.rb, lib/sprockets/railtie.rb, test/test_sourcemapping_url_processor.rb
If you prepare a JavaScript file by a bundler that adds a sourceMappingURL comment line as the last in the file, Sprockets will append a semicolon to this comment, thus breaking the URL reference.
The sourceMappingURL will also reference a file that has not been digested yet.
This PR fixes both issues.
=> Process source mapping URLs be set by transpilers

lib/sprockets/rails/asset_url_processor.rb, test/test_asset_url_processor.rb
The newly added AssetUrlProcessor hides tracked dependencies. This can cause referenced digested assets to be excluded from the final output during `assets:precompile`.
This PR unhides those dependencies so all referenced assets are output to `public/assets/` properly.
=> expose dependencies from AssetUrlProcessor

lib/sprockets/rails/asset_url_processor.rb, test/test_asset_url_processor.rb
Fixes #478
Previously having this css:
```
src: url(./fontawesome/fa-brands-400.eot);
```
would be transformed into:
```
src: url(/./fontawesome/fa-brands-400.eot);
```
This strips off the unnecessary `./` so it will be:
```
src: url(/fontawesome/fa-brands-400.eot);
```
=> Strip away the relative path

lib/sprockets/rails/sourcemapping_url_processor.rb, test/test_sourcemapping_url_processor.rb
Includes a work-around for bug where if the sourcemap is nested two levels deep, it'll resolve as the source file that's being mapped, rather than the map itself by Sprockets. So `context.resolve("a/b/c.js.map")` will return `c.js` instead of `c.js.map`. This doesn't happen when the nesting is only one level deep, like `a/b.js/map` or if there's no nesting at all. This is a long-standing Sprockets bug we need to find and fix, but it predates this processor, though the processor tickles it.
Also, this makes sure that nested files that do no tickle the double+ nesting bug will be correctly mapped.
=> Fix sourcemapping url replacement

lib/sprockets/rails/asset_url_processor.rb, test/test_asset_url_processor.rb
Issue:
With source file like below and asset host as `//assets.example.com`
```css
@font-face {
src: url('<%= font_path('fontawesome-webfont.eot') %>');
}
```
would produce
```css
@font-face {
src:url(//assets.example.com/assets.example.com/assets/fontawesome-webfont-82ff0fe46a6f60e0ab3c4a9891a0ae0a1f7b7e84c625f55358379177a2dcb202.eot)
}
```
=> Fix protocol relative URLs amended accidentally

README.md, lib/sprockets/rails/asset_url_processor.rb, lib/sprockets/railtie.rb, test/test_railtie.rb
As reported in https://github.com/rails/sprockets-rails/issues/478 / https://github.com/rails/sprockets-rails/issues/486, the introduction of the `AssetUrlProcessor` in https://github.com/rails/sprockets-rails/pull/476 broke some folks' CSS assets when they upgraded beyond sprockets-rails v3.2.2, but it was not released in a new major version.
~To remedy this, let's make `AssetUrlProcessor` be opt-in for now with the plan to change it to opt-out in the next major version. In this PR, I'm proposing the addition of a new `assets.rewrite_css_urls` configuration option to control whether or not `AssetUrlProcessor` is registered. We can default it to `false` in sprockets-rails v3.x and change the default to `true` in v4.0.~
Per https://github.com/rails/sprockets-rails/pull/489#issuecomment-9885 …
=> Add `assets.resolve_assets_in_css_urls` configuration option to allow disabling `AssetUrlProcessor`

lib/sprockets/rails/quiet_assets.rb, test/test_quiet_assets.rb
The introduction of the quiet assets middleware assumes that `::Rails.logger` responds to `#silence`. For projects using incompatible logger objects, like Ruby's `Logger`, a (potentially confusing) `NoMethodError` is raised in development when `config.assets.quiet` is enabled. 
This change now provides an informative error message to help developers update their configured logger to take advantage of quiet asset logging.
Fixes #376
=> Add useful message for logger silence error

gemfiles/Gemfile.rails-5.2.x.sprockets-4.x, gemfiles/Gemfile.rails-6.0.x.sprockets-4.x
This pull request addresses this bundle install failure that is used in CI.
```ruby
% BUNDLE_GEMFILE=gemfiles/Gemfile.rails-6.0.x.sprockets-4.x bundle install
Fetching https://github.com/rails/sprockets.git
fatal: Needed a single revision
Git error: command `git rev-parse --verify master` in directory
/Users/yahonda/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/cache/bundler/git/sprockets-67c51ee2a2e0410ca1e13d6e1277668b7a11b6c3 has
failed.
Revision master does not exist in the repository https://github.com/rails/sprockets.git. Maybe you misspelled it?
If this error persists you could try removing the cache directory
'/Users/yahonda/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/cache/bundler/git/sprockets-67c51ee2a2e0410ca1e13d6e1277668b7a11b6c3'
%
```
=> Update rails/sprockets default branch from master to main

CONTRIBUTING.md
This pull request replaces `contributor`  with `YOUR-USERNAME` in the repository URL.
So that contributors can replace `YOUR-USERNAME` with their GitHub user account.
=> Use `YOUR-USERNAME` instead of `contributor` in the repository URL

.github/workflows/ci.yml, Gemfile
Also, this patch fixes CI failure on current master branch by fixing Gemfile referencing non-existing rack branch.
=> CI against Ruby 3.2

lib/sprockets/rails.rb, lib/sprockets/rails/helper.rb, lib/sprockets/railtie.rb, test/test_helper.rb
Rails 7.1 will deprecate using the singleton ActiveSupport::Deprecation instance (https://github.com/rails/rails/pull/47354). This defines one for the gem and uses it.
It's also added to the application's set of deprecators, allowing it to be configured along all the other deprecators.
cc @rafaelfranca
=> Use a dedicated ActiveSupport::Deprecation

lib/sprockets/rails.rb, lib/sprockets/rails/deprecator.rb, lib/sprockets/railtie.rb
With the release of sprockets-rails 3.5.0, our local test suite breaks with
```
NoMethodError:
undefined method `deprecator' for Sprockets::Rails:Module
/home/circleci/solidus/vendor/bundle/ruby/3.2.0/gems/sprockets-rails-3.5.0/lib/sprockets/railtie.rb:129:in `block in <class:Railtie>'
```
This should fix that by explicitly requiring the
`Sprockets::Rails.deprecator` in both `lib/sprockets/rails.rb` and `lib/sprockets/railtie.rb`.
Fix #524
=> Require sprockets deprecator in Railtie

sprockets-rails.gemspec
Documented here: https://guides.rubygems.org/specification-reference/#metadata 
Useful for running https://github.com/MaximeD/gem_updater
=> Add changelog_uri to gemspec

test/test_helper.rb
Some applications or gems don't require sprockets/rails, instead they load sprockets/railtie.
This change catches this issue when running tests.
```console
$ git checkout v3.5.0
HEAD is now at 5f6d88d Release 3.5.0
$ git cherry-pick --no-commit prevent-regression-for-sprockets-railtie 
$ bundle exec rake >/dev/null 2>&1 || echo failed
failed
```
=> Prevent regressions with requiring sprockets/railtie

lib/sprockets/rails/quiet_assets.rb
This commit addresses the `warning: literal string will be frozen in the future` against Ruby 3.4.0dev
```$ ruby -v
ruby 3.4.0dev (2024-10-21T16:48:53Z master 5131fb5dbe) +PRISM [x86_64-linux]
$ RUBYOPT="--debug-frozen-string-literal" bundle exec rake test TEST=test/test_quiet_assets.rb
```
- Warnings addressed by this commit
```ruby
/path/to/sprockets-rails/lib/sprockets/rails/quiet_assets.rb:24: warning: literal string will be frozen in the future
/path/to/sprockets-rails/lib/sprockets/rails/quiet_assets.rb:23: info: the string was created here
```
- Sprockets Rails requires Ruby 2.5 that supports `<<~` (squiggly heredoc) introduced since Ruby 2.3.
https://www.ruby-lang.org/en/news/2015/12/25/ruby-2-3-0-released/ https://github.com/ruby/ruby/blob/d40ea2afa6ff5a6e5befcf342fb7b6dc58796b20/ …
=> Use `<<~ `(squiggly heredoc) to address `warning: literal string will be frozen in the future`
